// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDWiOaT34MKpW2G2oYUV8HsSBPeJsVnM',
    appId: '1:308276189030:web:c78a2ad41fb51944831aa7',
    messagingSenderId: '308276189030',
    projectId: 'edu-track-25ac9',
    authDomain: 'edu-track-25ac9.firebaseapp.com',
    storageBucket: 'edu-track-25ac9.firebasestorage.app',
    measurementId: 'G-ZE0LL11REE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxqgWC6fY08aSTVQBoCpkzV-s1zK4Nvs',
    appId: '1:308276189030:android:962c91935e5b370a831aa7',
    messagingSenderId: '308276189030',
    projectId: 'edu-track-25ac9',
    storageBucket: 'edu-track-25ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-rG24i-GYzJuaMzFSmdPmGfBx3HlU8U',
    appId: '1:308276189030:ios:95d78e40f4e63113831aa7',
    messagingSenderId: '308276189030',
    projectId: 'edu-track-25ac9',
    storageBucket: 'edu-track-25ac9.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-rG24i-GYzJuaMzFSmdPmGfBx3HlU8U',
    appId: '1:308276189030:ios:95d78e40f4e63113831aa7',
    messagingSenderId: '308276189030',
    projectId: 'edu-track-25ac9',
    storageBucket: 'edu-track-25ac9.firebasestorage.app',
    iosBundleId: 'com.example.edutrackApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEDWiOaT34MKpW2G2oYUV8HsSBPeJsVnM',
    appId: '1:308276189030:web:765bfd1d88869abc831aa7',
    messagingSenderId: '308276189030',
    projectId: 'edu-track-25ac9',
    authDomain: 'edu-track-25ac9.firebaseapp.com',
    storageBucket: 'edu-track-25ac9.firebasestorage.app',
    measurementId: 'G-NG0DEWHMGD',
  );
}
